# Generated by Django 3.0.4 on 2020-03-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mfa_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email Address')),
                ('password', models.CharField(max_length=254, verbose_name='Hashed User Password')),
                ('hotp_secret', models.CharField(max_length=254, verbose_name='Hashed HOTP Secret')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of Registration')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
                'db_table': 'mfa_users',
            },
        ),
    ]
