# Generated by Django 3.0.4 on 2020-03-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mfa_user',
            new_name='MFAUser',
        ),
    ]
