# Generated by Django 3.0.4 on 2020-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_user', '0002_auto_20200318_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfauser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Whether Account is Confirmed'),
        ),
    ]
