# Generated by Django 3.0.4 on 2020-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_user', '0003_mfauser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfauser',
            name='hotp_count',
            field=models.IntegerField(default=0, verbose_name='Current HOTP Counter Value'),
        ),
    ]
