# Generated by Django 3.0.5 on 2020-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfa_user', '0004_mfauser_hotp_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfauser',
            name='hotp_secret',
            field=models.BinaryField(verbose_name='Encrypted HOTP Secret'),
        ),
    ]
